image: docker:latest  # Usar la imagen oficial de Docker que incluye el cliente Docker

services:
  - docker:dind  # Este servicio proporciona el Docker daemon dentro del contenedor

stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: "app"
  DOCKER_REGISTRY: "docker.io"
  DOCKER_TLS_CERTDIR: "/certs"  # Esto es necesario cuando usamos DinD, ayuda a configurar el TLS en Docker

before_script:
  - apk add --no-cache curl  # Instalar curl (o cualquier otra herramienta que necesites)

build:
  stage: build
  script:
    - docker info  # Verifica si Docker está funcionando correctamente
    - docker login -u $CI_USER -p $CI_PSW
    - docker build -t $DOCKER_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME .
  only:
    - main
