image: "python:3.12"

stages:
  - build
  - test
  - deploy


variables:
  IMAGE_NAME: "app"
  DOCKER_REGISTRY: "docker.io"


build:
  stage: build
  script:
    - docker login -u $CI_USER -p $CI_PSW

    - docker build -t $DOCKER_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME .
  only:
    - main
    - tags